export const GET_ERRORS = 'GET_ERRORS';
export const LOADING = 'LOADING';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_REGISTERED_USER = 'SET_REGISTERED_USER';
export const CREATE_REQUEST = 'CREATE_REQUEST';
export const REQUEST_LOADING = 'REQUEST_LOADING';
